### PR TITLE
Update on Styling

### PR DESCRIPTION
**Pull request by yow008**

### CODE REVIEW

**Review by zhongtiff — COMMENTED** [review]
looks good

**Review by zhongtiff — COMMENTED** [review]
Changes reviewed

**Comment by hannahhui5184** [comment]
Why do your files look like they're deleting and adding the same things? Have you been able to pull from main?

Also please make sure to merge your file(s), or ask for help doing so if you need. Otherwise the tests will not be run and you cannot tell right away if you need to fix something. Ignore the codeclimate test but everything else is required to pass.

**Comment by yow008** [comment]
I don't know why a js file in my code caused this failing test, so I just reverted that file to be the same as the one on the main branch, but that js file still couldn't pass this test. Then, I asked Tiffany to help reviewing that.
> Main Branch Linting & Formatting / js-eslint (pull_request)

**Review by zhongtiff — APPROVED** [review]
reviewed changes

**Pull request merged**
